In [4]:
import numpy as np
import torch
import torch.utils.data
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
from RBM_helper import RBM
import gzip
import pickle

## Define Epochs, Batch Size and GPU support

In [5]:
batch_size = 128
epochs = 200
gpu = False

## Define Dummy Training Set

For a first test we define a training set, which contains the strings `[1,0,1,0,...]` and `[0,1,0,1,...]` with equal probability and we will train an RBM on them.
After the training we can sample from the RBM and we should get these two strings with equal probability.

In [8]:
#DUMMY TRAINING SET
# ------------------------------------------------------------------------------
#define a simple training set and check if rbm.draw() returns this after training.
data = np.array([[1,0,1,0,1,0,1,0,1,0]]*1000 + [[0,1,0,1,0,1,0,1,0,1]]*1000)
np.random.shuffle(data)
data = torch.FloatTensor(data)
# ------------------------------------------------------------------------------

## Define RBM and Data Loader

We define the RBM and choose 10 visible units (because the input data is 10 dimensional) and 10 hidden units. `k=1` indicates how many Gibbs sampling steps we make during the training.

In [ ]:
vis = len(data[0]) #input dimension

rbm = RBM(n_vis = vis, n_hin = vis, k=1, gpu = gpu)
if gpu:
    rbm = rbm.cuda()
    all_spins = all_spins.cuda()

train_loader = torch.utils.data.DataLoader(data, batch_size=batch_size,
                                           shuffle=True)

## Train RBM

In [ ]:
for epoch in range(epochs):
    train_loader = torch.utils.data.DataLoader(data, batch_size=batch_size,
                                               shuffle=True)
    print(epoch)
    momentum = 1 - 0.1*(epochs-epoch)/epochs #starts at 0.9 and goes up to 1
    lr = (0.1*np.exp(-epoch/epochs*10))+0.0001
    rbm.train(train_loader, lr = lr, momentum = momentum)

## Sample from trained RBM

Draw 10 samples from RBM and print them. If the training was successful, they should be one of the training samples. You can also increase the number of samples and count how often each sample appears. They should be equally likely, because they are also equally likely in the training set.

In [14]:
nr_samples = 10
print('DRAW SAMPLES')
for i in range(nr_samples):
    a = rbm.draw_sample(10)
    print(a.detach().numpy())   

DRAW SAMPLES
[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
